[package]
name = "starknet-rust-contract"
version = "0.16.0"
authors = ["Software Mansion", "Jonathan LEI <me@xjonathan.dev>"]
license = "MIT OR Apache-2.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/software-mansion-labs/starknet-rs"
description = """
Types and utilities for Starknet smart contract deployment and interaction
"""
keywords = ["ethereum", "starknet", "web3"]
exclude = ["test-data/**"]

[dependencies]
starknet-rust-core = { version = "0.16.0", path = "../starknet-rust-core" }
starknet-rust-providers = { version = "0.16.0", path = "../starknet-rust-providers" }
starknet-rust-accounts = { version = "0.16.0", path = "../starknet-rust-accounts" }
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
serde_with = "3.9.0"
thiserror = "1.0.40"

[dev-dependencies]
rand = { version = "0.8.5", features=["std_rng"] }
starknet-rust-signers = { version = "0.14.0", path = "../starknet-rust-signers" }
tokio = { version = "1.27.0", features = ["full"] }
url = "2.3.1"

[lints]
workspace = true
