[package]
name = "starknet-rust-contract"
version = "0.17.0"
authors.workspace = true
license.workspace = true
edition.workspace = true
readme.workspace = true
repository.workspace = true
description = """
Types and utilities for Starknet smart contract deployment and interaction
"""
keywords.workspace = true
exclude = ["test-data/**"]

[dependencies]
starknet-rust-core.workspace = true
starknet-rust-providers.workspace = true
starknet-rust-accounts.workspace = true
serde_json.workspace = true

[dev-dependencies]
starknet-rust-signers.workspace = true
tokio.workspace = true
test-common.workspace = true

[lints]
workspace = true
