on:
  push:
    branches:
      - master
  pull_request:

name: Tests
jobs:
  unix-test:
    name: Unix tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-14]
        toolchain: [stable, nightly]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          override: true

      - name: Test starknet-rust-crypto with pedersen_no_lookup
        run: |
          cargo test -p starknet-rust-crypto --features pedersen_no_lookup

      - name: Run cargo tests
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 20
          retry_wait_seconds: 30
          command: STARKNET_RPC=${{ secrets.NODE_URL }} cargo test --all

  win-test:
    name: Windows tests
    runs-on: windows-latest
    strategy:
      matrix:
        toolchain: [stable, nightly]
        target: [x86_64-pc-windows-gnu, x86_64-pc-windows-msvc]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}
          profile: minimal
          override: true

      - name: Test starknet-rust-crypto with pedersen_no_lookup
        run: |
          cargo test -p starknet-rust-crypto --features pedersen_no_lookup

      - name: Run cargo tests
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 20
          retry_wait_seconds: 30
          command: $env:STARKNET_RPC = "${{ secrets.NODE_URL }}"; cargo test --all --target ${{ matrix.target }} --exclude starknet-rust-cxx

  wasm-test:
    name: WASM tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Add wasm32-unknown-unknown target
        run: |
          rustup target add wasm32-unknown-unknown

      - name: Build project
        run: |
          cargo build --all --target wasm32-unknown-unknown \
            --exclude starknet-rust-cxx \
            --exclude starknet-rust-tokio-tungstenite

      - name: Install wasm-pack
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: wasm-pack

      - name: Run starknet-rust-crypto tests
        run: |
          (cd ./starknet-rust-crypto && wasm-pack test --release --node)

      - name: Run starknet-rust-core tests
        run: |
          (cd ./starknet-rust-core && wasm-pack test --release --node)

      - name: Run starknet-rust-signers tests
        run: |
          (cd ./starknet-rust-signers && wasm-pack test --release --node)

      - name: Run starknet-rust-macros tests
        run: |
          (cd ./starknet-rust-macros && wasm-pack test --release --node)

  no-std-build:
    name: no-std build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Add --target thumbv6m-none-eabi target
        run: |
          rustup target add thumbv6m-none-eabi

      - name: Build starknet-rust-crypto
        run: |
          cargo build --package starknet-rust-crypto \
            --target thumbv6m-none-eabi \
            --no-default-features

          cargo build --package starknet-rust-crypto \
            --target thumbv6m-none-eabi \
            --no-default-features \
            --features alloc

      - name: Build starknet-rust-core
        run: |
          cargo build --package starknet-rust-core \
            --target thumbv6m-none-eabi \
            --no-default-features

  ledger:
    name: Ledger tests
    runs-on: ubuntu-latest
    container: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-dev-tools

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install stable Rust toolchain
        run: |
          rustup toolchain install stable
          rustup default stable

      - name: Run starknet-rust-signers tests
        env:
          STARKNET_RPC: ${{ secrets.NODE_URL }}
        run: |
          cargo test --package starknet-rust-signers \
            ledger:: \
            -- --ignored

      - name: Run starknet-rust-accounts tests
        env:
          STARKNET_RPC: ${{ secrets.NODE_URL }}
        run: |
          cargo test --package starknet-rust-accounts \
            ledger:: \
            -- --ignored
